### ISSUE TITLE
Feature Request: Thumbnail Viewer Should Show All Images in Source Folder

### ISSUE THREAD

**Issue by don1138** [Automaticism/Promptvision#12]
# Is your feature request related to a problem? Please describe.
The Thumbnail section shows a maximum of 112 images.

Currently, clicking the left/right arrows in the `metadata` section load the next in sequence, and removes the thumb of the previous image from position 1 in the thumbnails viewer.

# Describe the solution you'd like
I'd like to have access to all thumbnails at all times.

And having them sorted alphabetically by subfolder & name would be helpful.

Showing all 600 at once might be a bit too much, so maybe they get broken up into pages of 100?

# Describe alternatives you've considered

# Additional context

**Comment by Automaticism** [comment]
Thumbnails update correctly now. Kept liliting initial load. Scroll and its loads more. This is useful for weaker PCs and when you are quickly browsing through images. 

Additionally added border around active image thumbnail. Sorted the thumbnails aswell. On folder and name.
