### ISSUE TITLE
Feature Request: Word Wrap File Path Names

### ISSUE THREAD

**Issue by don1138** [Automaticism/Promptvision#13]
# Is your feature request related to a problem? Please describe.
Some of the path names of my images are very long and include underscores, which forces the layout of the `metadata` section to redraw extra wide on some images, then back to normal on others.

# Describe the solution you'd like

Add `word-wrap: anywhere;` to `.metadata-table td` so that unwieldy names don't break the layout.

```
.metadata-table td {
  padding: 12px 16px;
  color: #FFF;
  border: none;
  word-wrap: anywhere;
}
```

# Describe alternatives you've considered
Since this would affect the list of **Prompt** tags as well, maybe just assign a special class tot he file path field and just apply it there.

# Additional context
Adding `text-align: left;` to all fields would be nice. It's easier to scan the data when it's aligned left rather than centered.

**Comment by Automaticism** [comment]
Text should be left aligned. Wrap added.
