### ISSUE TITLE
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

### ISSUE THREAD

**Issue by TheOctonaut** [Automaticism/Promptvision#37]
**Describe the bug**
Installing in Windows 10 not working, pip requirements install gives warning about ConfigParser

**To Reproduce**

Follow steps provided in Civitai.com description
Reach step 5: pip install -r requirements.txt

**Expected behavior**
Pip installs the requirements

**Screenshots**
 AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows 10
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] Latest commit https://github.com/Automaticism/Promptvision/commit/5dcc03cfb842693b8b7b98e4159821cd0d21b6c2

**Comment by Automaticism** [comment]
Which python version are you running? 

Just tested again on my 3.11.6 install and it works in my venv.

Did a clone and new venv setup. It works here on 3.11.6.
