### ISSUE TITLE
Possible Typo in Script? (sdparsers -> sd_parsers)

### ISSUE THREAD

**Issue by AsaTyr2018** [Automaticism/Promptvision#38]
**Describe the bug**
On Launch i get a pip error of a missing module
Manual install of Module failed:
pip install sdparsers
ERROR: Could not find a version that satisfies the requirement sdparsers (from versions: none)

Done some research and found only this:
https://pypi.org/project/sd-parsers/

**To Reproduce**

Simple launching on my Linux Ubuntu Server and go Web

**Expected behavior**
Following all Instructions -> working

**Screenshots**
![grafik](https://github.com/user-attachments/assets/ed6246ef-5cda-4442-94f3-bf53a281bfe6)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Edge, Chrome, Firefox

**Additional context**
Tried to fix myself but changing the code from sdpharsers to sd_parsers send more errors.

**Comment by Automaticism** [comment]
Not relevant anymore with the rewrite. It should now use pypng to get the exif prompt information.
