### ISSUE TITLE
Does not read Prompt embedded in JPG files

### ISSUE THREAD

**Issue by MrKuenning** [Automaticism/Promptvision#5]
**Describe the bug**
I have tens of thousands of AI-generated files, I use JPG for space purposes and I have been looking for a tool that will let me organize / rename / sort / file / tag those files. 

**To Reproduce**
 I loaded up prompt vision and pointed it at a folder with a few hundred images and it quickly loaded and displayed the images, but they all said there was no prompt information.

**Expected behavior**
All of the imaages show the prompt information if viewed in the A1111 PNG info tab.  I expected this display the prompt information.

**Screenshots**
![2023-03-23 18_55_29-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16549268/227412672-f7400d45-d261-4f45-a70f-f07e877d4998.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 111

**Comment by Automaticism** [comment]
Can you upload one ore more example JPGs? 
It's easier to test extraction if I have test objects.

**Comment by MrKuenning** [comment]
![2023-03-19 105305 - 273133096 - 512x704 - c7 s30 - Brad Pitt, , ,popularmechanics](https://user-images.githubusercontent.com/16549268/227672784-49fb39b4-f9e9-46f0-a9e3-d0c46412c7a6.jpg)


![2023-03-20 210608 - 4091345841 - 768x768 - c cfg  s steps  -  prompt_no_styles -before-highres-fix](https://user-images.githubusercontent.com/16549268/227673265-9106fc32-8c95-4626-b5e0-d99b5910aaef.jpg)
