### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by Mirabilis1729** [Automaticism/Promptvision#9]
The ability to delete images would be a godsend when reviewing

**Comment by Automaticism** [comment]
I am thinking of adding support for this aswell as a flag that will mark every image as "reviewed=False" upon loading a new folder. So when you browse it will be set to True if you've browsed the image(s). 
You'll also be able to sort on this.

This should also make it possible to make e.g. deleting all images that are seen and with rating=1.

**Comment by Automaticism** [comment]
Added to roadmap in #20.
